# Generated by Django 6.0 on 2025-12-25 08:40

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nodeid', models.CharField(db_index=True, help_text="Unique sensor node identifier (e.g., 'sensor_zone1')", max_length=100, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, help_text='Optional human-readable name for the sensor', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this sensor is currently active')),
            ],
            options={
                'verbose_name': 'Sensor',
                'verbose_name_plural': 'Sensors',
                'db_table': 'Sensor',
                'ordering': ['nodeid'],
            },
        ),
        migrations.CreateModel(
            name='SystemMode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('MANUAL', 'Manual'), ('AUTOMATIC', 'Automatic')], default='AUTOMATIC', help_text='System mode: MANUAL or AUTOMATIC', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Mode',
                'verbose_name_plural': 'System Mode',
                'db_table': 'SystemMode',
            },
        ),
        migrations.CreateModel(
            name='ThresholdConfig',
            fields=[
                ('sensor', models.OneToOneField(help_text='Sensor this threshold config applies to (1:1 relationship)', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='threshold', serialize=False, to='soil_moisture.sensor')),
                ('low_threshold', models.FloatField(default=30.0, help_text='Moisture level below which motor turns ON', validators=[django.core.validators.MinValueValidator(0.0, message='Low threshold cannot be negative'), django.core.validators.MaxValueValidator(100.0, message='Low threshold cannot exceed 100%')])),
                ('high_threshold', models.FloatField(default=70.0, help_text='Moisture level above which motor turns OFF', validators=[django.core.validators.MinValueValidator(0.0, message='High threshold cannot be negative'), django.core.validators.MaxValueValidator(100.0, message='High threshold cannot exceed 100%')])),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Threshold Configuration',
                'verbose_name_plural': 'Threshold Configuration',
                'db_table': 'ThresholdConfig',
            },
        ),
        migrations.CreateModel(
            name='Motor',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Human-readable name for the motor (e.g., 'Pump 1', 'Zone A Motor')", max_length=100)),
                ('state', models.CharField(choices=[('ON', 'On'), ('OFF', 'Off')], default='OFF', help_text='Current state of the motor (ON/OFF)', max_length=3)),
                ('sensor', models.OneToOneField(help_text='Sensor this motor is mapped to (1:1 relationship)', on_delete=django.db.models.deletion.CASCADE, related_name='motor', to='soil_moisture.sensor')),
            ],
            options={
                'db_table': 'Motor',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['state'], name='Motor_state_6d8782_idx'), models.Index(fields=['name'], name='Motor_name_bd2324_idx'), models.Index(fields=['sensor'], name='Motor_sensor__344a9f_idx')],
            },
        ),
        migrations.CreateModel(
            name='SoilMoisture',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.FloatField(help_text='Soil moisture value (percentage 0-100)', validators=[django.core.validators.MinValueValidator(0.0, message='Moisture value cannot be negative'), django.core.validators.MaxValueValidator(100.0, message='Moisture value cannot exceed 100%')])),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Timestamp when the reading was taken')),
                ('ip_address', models.CharField(blank=True, help_text='IP address of the device sending data', max_length=45, null=True)),
                ('sensor', models.ForeignKey(help_text='Sensor that recorded this reading', on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='soil_moisture.sensor')),
            ],
            options={
                'verbose_name': 'Soil Moisture Reading',
                'verbose_name_plural': 'Soil Moisture Readings',
                'db_table': 'SoilMoisture',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='SoilMoistur_timesta_73cf26_idx'), models.Index(fields=['sensor'], name='SoilMoistur_sensor__ea053f_idx'), models.Index(fields=['ip_address'], name='SoilMoistur_ip_addr_c54609_idx')],
            },
        ),
    ]
