# Generated by Django 6.0 on 2025-12-25 09:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soil_moisture', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thresholdconfig',
            name='high_threshold',
        ),
        migrations.RemoveField(
            model_name='thresholdconfig',
            name='low_threshold',
        ),
        migrations.AddField(
            model_name='thresholdconfig',
            name='threshold',
            field=models.FloatField(default=50.0, help_text='Motor turns ON when moisture value exceeds this threshold', validators=[django.core.validators.MinValueValidator(0.0, message='Threshold cannot be negative'), django.core.validators.MaxValueValidator(100.0, message='Threshold cannot exceed 100%')]),
        ),
    ]
